import { z } from 'zod';
import {
  ILLMClient,
  LLMStructuredRequest,
  LLMStructuredResponse,
  LLMAuthError,
  LLMConfigurationError,
  LLMRateLimitError,
  LLMResponseFormatError,
  LLMTimeoutError,
  LLMError
} from './llm-client.interface';

export interface GeminiLLMClientOptions {
  apiKey?: string;
  baseUrl?: string;
  model?: string;
  timeoutMs?: number;
  maxRetries?: number;
  sleepFn?: (ms: number) => Promise<void>;
}

/**
 * Strips JSON Schema keywords unsupported by the Gemini OpenAPI 3.0 schema subset.
 * Removes $schema and additionalProperties recursively.
 */
function cleanGeminiSchema(schema: unknown): unknown {
  if (!schema || typeof schema !== 'object') {
    return schema;
  }

  if (Array.isArray(schema)) {
    return schema.map(cleanGeminiSchema);
  }

  const result: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(schema as Record<string, unknown>)) {
    if (key === '$schema' || key === 'additionalProperties' || key === 'default') {
      continue;
    }
    result[key] = cleanGeminiSchema(value);
  }

  // Handle array types like type: ['string', 'null'] generated by Zod nullable schemas
  if (Array.isArray(result.type)) {
    const types = result.type as string[];
    const isNullable = types.includes('null');
    const mainType = types.find((t) => t !== 'null') || 'string';
    result.type = mainType;
    if (isNullable) {
      result.nullable = true;
    }
  }

  // Handle anyOf with null branch generated by Zod enum().nullable()
  if (Array.isArray(result.anyOf)) {
    const anyOfList = result.anyOf as Array<Record<string, unknown>>;
    const nullBranch = anyOfList.find(
      (b) => b && (b.type === 'null' || (Array.isArray(b.type) && b.type.includes('null')))
    );
    const mainBranch = anyOfList.find(
      (b) =>
        b && b.type !== 'null' && (!Array.isArray(b.type) || !b.type.every((t) => t === 'null'))
    );
    if (nullBranch && mainBranch) {
      delete result.anyOf;
      Object.assign(result, mainBranch);
      result.nullable = true;
    }
  }

  return result;
}

export class GeminiLLMClient implements ILLMClient {
  readonly providerId = 'gemini';
  readonly modelId: string;
  private readonly apiKey: string;
  private readonly baseUrl: string;
  private readonly timeoutMs: number;
  private readonly maxRetries: number;
  private readonly sleepFn: (ms: number) => Promise<void>;

  constructor(options: GeminiLLMClientOptions = {}) {
    this.apiKey = options.apiKey !== undefined ? options.apiKey : process.env.GEMINI_API_KEY || '';
    this.baseUrl = (
      options.baseUrl ||
      process.env.GEMINI_BASE_URL ||
      'https://generativelanguage.googleapis.com/v1beta'
    ).replace(/\/+$/, '');
    this.modelId =
      options.model || process.env.LLM_MODEL || process.env.GEMINI_MODEL || 'gemini-3.8-flash';
    this.timeoutMs = options.timeoutMs ?? 25000;
    this.maxRetries = options.maxRetries ?? 2;
    this.sleepFn =
      options.sleepFn ?? ((ms: number) => new Promise((resolve) => setTimeout(resolve, ms)));
  }

  async generateStructured<T>(request: LLMStructuredRequest<T>): Promise<LLMStructuredResponse<T>> {
    if (!this.apiKey) {
      throw new LLMConfigurationError(
        'GEMINI_API_KEY is not configured. Please set GEMINI_API_KEY in environment variables.'
      );
    }

    // Convert Zod schema to clean JSON schema for Gemini structured output
    const rawJsonSchema = (z.toJSONSchema ? z.toJSONSchema(request.schema) : {}) as Record<
      string,
      unknown
    >;
    const cleanSchema = cleanGeminiSchema(rawJsonSchema);

    const body = {
      systemInstruction: {
        parts: [{ text: request.systemPrompt }]
      },
      contents: [
        {
          role: 'user',
          parts: [{ text: request.userPrompt }]
        }
      ],
      generationConfig: {
        responseMimeType: 'application/json',
        responseSchema: cleanSchema,
        temperature: request.temperature ?? 0.1,
        ...(request.maxTokens ? { maxOutputTokens: request.maxTokens } : {})
      }
    };

    let attempt = 0;
    const startTime = Date.now();

    while (attempt <= this.maxRetries) {
      attempt++;
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), this.timeoutMs);

      try {
        const url = `${this.baseUrl}/models/${encodeURIComponent(this.modelId)}:generateContent`;
        const response = await fetch(url, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-goog-api-key': this.apiKey
          },
          body: JSON.stringify(body),
          signal: controller.signal
        });

        clearTimeout(timer);

        if (!response.ok) {
          const status = response.status;
          let errorText = '';
          try {
            const errorJson = await response.json();
            errorText = errorJson?.error?.message || JSON.stringify(errorJson);
          } catch {
            errorText = await response.text();
          }

          // Sanitize error text to ensure no accidental key leakage
          const sanitizedError = errorText.replace(/[a-zA-Z0-9_-]{20,}/g, '[REDACTED]');

          if (
            status === 401 ||
            status === 403 ||
            (status === 400 &&
              (sanitizedError.toLowerCase().includes('api key') ||
                sanitizedError.toLowerCase().includes('api_key')))
          ) {
            throw new LLMAuthError(`Gemini Authentication Failed: ${sanitizedError}`);
          }

          if (status === 429 || sanitizedError.includes('RESOURCE_EXHAUSTED')) {
            if (attempt <= this.maxRetries) {
              const retryAfterHeader = response.headers?.get?.('retry-after');
              const retryAfterSeconds = retryAfterHeader ? parseFloat(retryAfterHeader) : null;
              const msgMatch = sanitizedError.match(/retry (?:in|after) ([0-9.]+)s?/i);
              const msgSeconds = msgMatch ? parseFloat(msgMatch[1]) : null;
              const delaySeconds = retryAfterSeconds || msgSeconds;
              const backoffMs =
                delaySeconds && !isNaN(delaySeconds)
                  ? Math.min(Math.ceil(delaySeconds * 1000) + 1000, 60000)
                  : Math.pow(2, attempt - 1) * 1000;

              await this.sleepFn(backoffMs);
              continue;
            }
            throw new LLMRateLimitError(`Gemini Rate Limit Exceeded (HTTP 429): ${sanitizedError}`);
          }

          if (status >= 500 && status <= 599) {
            if (attempt <= this.maxRetries) {
              const backoffMs = Math.pow(2, attempt - 1) * 1000;
              await this.sleepFn(backoffMs);
              continue;
            }
            throw new LLMError(
              `Gemini Service Error (HTTP ${status}): ${sanitizedError}`,
              'SERVICE_ERROR',
              status
            );
          }

          throw new LLMError(
            `Gemini API Error (HTTP ${status}): ${sanitizedError}`,
            'API_ERROR',
            status
          );
        }

        const json = await response.json();
        const candidate = json?.candidates?.[0];

        if (!candidate) {
          const blockReason = json?.promptFeedback?.blockReason || 'No candidate returned';
          throw new LLMResponseFormatError(`Gemini returned no candidates: ${blockReason}`);
        }

        const rawContent = candidate.content?.parts?.[0]?.text;
        if (!rawContent || typeof rawContent !== 'string') {
          throw new LLMResponseFormatError('Gemini response candidate contained no text content');
        }

        let parsedJson: unknown;
        try {
          parsedJson = JSON.parse(rawContent.trim());
        } catch (parseError) {
          throw new LLMResponseFormatError(
            `Failed to parse Gemini response as JSON: ${parseError instanceof Error ? parseError.message : String(parseError)}`
          );
        }

        const parseResult = request.schema.safeParse(parsedJson);
        if (!parseResult.success) {
          throw new LLMResponseFormatError(
            `Gemini response does not conform to requested schema: ${parseResult.error.message}`
          );
        }

        const usage = json.usageMetadata;
        return {
          data: parseResult.data,
          rawJson: rawContent,
          metadata: {
            provider: this.providerId,
            model: this.modelId,
            extractionVersion: 'resume-extraction-v1',
            latencyMs: Date.now() - startTime,
            promptTokens: usage?.promptTokenCount,
            completionTokens: usage?.candidatesTokenCount,
            totalTokens: usage?.totalTokenCount
          }
        };
      } catch (err: unknown) {
        clearTimeout(timer);

        if (err instanceof LLMError || (err as { name?: string })?.name?.startsWith('LLM')) {
          throw err;
        }

        if (err instanceof Error && err.name === 'AbortError') {
          throw new LLMTimeoutError(
            `Gemini request timed out after ${this.timeoutMs}ms (model: ${this.modelId})`
          );
        }

        throw new LLMError(
          `Unexpected Gemini invocation failure: ${err instanceof Error ? err.message : String(err)}`,
          'INVOCATION_ERROR',
          500
        );
      }
    }

    throw new LLMError(
      `Gemini request failed after ${this.maxRetries} retries`,
      'MAX_RETRIES_EXCEEDED',
      500
    );
  }
}
